### ISSUE TITLE
Add support for :nth-child `of <selector>` support

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-css#13]
See https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child.#the_of_selector_syntax

Current state:
![of <selector> current rendering](https://github.com/microsoft/vscode-css/assets/76149603/ad2a79d8-1f66-4960-9fd3-33c7f3264569)

**Comment by romainmenke** [comment]
```css
.foo article:nth-child(1 of .not-hidden) {}
.foo article:nth-child(2 of .not-hidden) {}
.foo article:nth-child(3 of .not-hidden) {}
.foo article:nth-child(4 of .not-hidden) {}
.foo article:nth-child(n + 5 of .not-hidden) {}
```
