### ISSUE TITLE
Should `layer` be syntax highlighted?

### ISSUE THREAD

**Issue by TylerLeonhardt** [microsoft/vscode-css#24]
```css
@import url('bootstrap/scss/bootstrap.scss') layer(bootstrap);
```
 _Originally posted by @TylerLeonhardt in [#180631](https://github.com/microsoft/vscode/issues/180631#issuecomment-1832672996)_

**Comment by andreamah** [comment]
duplicate of https://github.com/microsoft/vscode-css/issues/17
